In [1]:
import numpy as np
from numpy import linalg
import matplotlib.pyplot as plt

In [2]:
a = np.array([[2, 4,3], [0, 2,1],[4,2,3]])
print(a)
np.linalg.det(a)

[[2 4 3]
 [0 2 1]
 [4 2 3]]


0.0

In [3]:
b = np.array([[0, 4], [2, 4]])
print(b)
np.linalg.det(b)

[[0 4]
 [2 4]]


-7.999999999999998

In [4]:
c = np.array([[3,3], [7, 8]])
print(c)
np.linalg.det(c)

[[3 3]
 [7 8]]


2.9999999999999982

In [5]:
d = np.linalg.det(2*a) - np.linalg.det((b-c)/2)
d

-4.250000000000001